export const ConstantRoutes = {
  NOTFOUND: "*",
  DASHBOARD: "/",
  LOGIN: "/admin_login",
  ALL_ORDERS: "/orders",
  ALL_PRODUCTS: "/product/admin-products",
  ADD_PRODUCT: "/product/new",
  EDIT_PRODUCT: "/editProduct/:id",
  PROFILE: "/profile",
  SHOPPING_CART: "/shoppingCart",
  REVIEW_ORDER: "/reviewOrder",
  SUGGESTION: "/Suggestion",
  HELP: "/help",
  ALL_COUPONS: "/payment/all-coupons",
  CREATE_COUPON: "/payment/coupon-create",
};
